export const cujHotspots = [
  // 🏫 In-Campus
  { id: 'main-gate', name: 'Main Gate', group: 'Inside Campus' },
  { id: 'bus-stop-outside', name: 'Bus stop (outside the main gate)', group: 'Inside Campus' },
  { id: 'bus-stop-dde', name: 'Bus stop (in front of DDE)', group: 'Inside Campus' },
  { id: 'dde-building', name: 'DDE building', group: 'Inside Campus' },
  { id: 'dde-badminton', name: 'DDE Badminton court', group: 'Inside Campus' },
  { id: 'registrar-office', name: 'Registrar office', group: 'Inside Campus' },
  { id: 'tunnel', name: 'Tunnel', group: 'Inside Campus' },
  { id: 'water-tank', name: 'Water tank above tunnel', group: 'Inside Campus' },
  { id: 'sports-ground', name: 'Sports ground', group: 'Inside Campus' },
  { id: 'canteen', name: 'Canteen', group: 'Inside Campus' },
  { id: 'tapri', name: 'Tapri', group: 'Inside Campus' },
  { id: 'academic-block', name: 'Academic block', group: 'Inside Campus' },
  { id: 'vc-kothi', name: 'VC ki kothi', group: 'Inside Campus' },
  { id: 'pfab-building', name: 'P.Fab building', group: 'Inside Campus' },
  { id: 'spm-boys-hostel', name: 'SPM Boys Hostel', group: 'Inside Campus' },
  { id: 'pmm-building', name: 'PMM building', group: 'Inside Campus' },
  { id: 'spm-badminton', name: 'SPM Badminton court', group: 'Inside Campus' },
  { id: 'spm-gym', name: 'SPM Gym', group: 'Inside Campus' },
  { id: 'isro-building', name: 'ISRO building', group: 'Inside Campus' },
  { id: 'science-block', name: 'Science block', group: 'Inside Campus' },
  { id: 'drdo', name: 'DRDO', group: 'Inside Campus' },
  { id: 'professors-quarters', name: 'Professor\'s Quarters', group: 'Inside Campus' },
  { id: 'girls-hostel', name: 'Girls Hostel', group: 'Inside Campus' },
  { id: 'auditorium', name: 'Brigadier Rajinder Singh Auditorium', group: 'Inside Campus' },
  { id: 'dde-library', name: 'DDE Library', group: 'Inside Campus' },
  { id: 'central-library', name: 'Central Library (under construction)', group: 'Inside Campus' },
  { id: 'abhinav-teela', name: 'Abhinav Teela', group: 'Inside Campus' },
  { id: 'baba-surgal-dev-mandir', name: 'Baba Surgal Dev Mandir', group: 'Inside Campus' },
  { id: 'masjid', name: 'Masjid (near CUJ village)', group: 'Inside Campus' },

  // 🏠 Outside-Campus
  { id: 'panini-boys-hostel', name: 'Panini Boys Hostel (Baribrahmna)', group: 'Outside Campus' },
  { id: 'sainik-colony-boys-hostel', name: 'Sainik Colony Boys Hostel', group: 'Outside Campus' },
  { id: 'vivekanand-boys-hostel', name: 'Vivekanand Boys Hostel', group: 'Outside Campus' },
  { id: 'funky-town', name: 'Funky Town', group: 'Outside Campus' },
  { id: 'sewa-restaurant', name: 'Sewa Restaurant', group: 'Outside Campus' },
  { id: 'back-banchers', name: 'Back Banchers', group: 'Outside Campus' },
  { id: 'rahya-chowk', name: 'Rahya Chowk', group: 'Outside Campus' },
  { id: 'rahya-morh', name: 'Rahya Morh', group: 'Outside Campus' },
  { id: 'rahya-morh-bus-stop', name: 'Rahya Morh Bus Stop', group: 'Outside Campus' }
]; 